### ISSUE TITLE
Unable to Fully Remove the Add-On

### ISSUE THREAD

**Issue by ghost** [sachingooo/anki-congrats-confetti#2]
I removed the "Congrats Confetti!" add-on from my Anki. However, it continues to play the applause sound after I finish a deck. 

I am currently using Version ⁨2.1.61. I attempted to update to the most updated Verson 23.10.1, which did not fix the issue.

**Comment by sachingooo** [comment]
Uhhh... are you _sure_ that this addon is the one that added the sound? That's not functionality that was ever included in this code.
